### PR TITLE
post WAAHS climb fixes/improvements

### LINKED ISSUE #85: Fix climb default command
Based on WAAHS E4 and E6 logs, it runs, but reportedly during testing "only ran once".

We should also add a name to the command.

### LINKED ISSUE #89: Fix climb inTolerance logging
Right now the value is updated once at the start and never updated again.

### LINKED ISSUE #90: Make separate climb speeds for different movement stages
This way, we can run faster on the way out and slower on the way in.

### PR DESCRIPTION
**Pull request by iamawesomecat**
Fixes #89 
Fixes #90 
Fixes #85

### CODE REVIEW

File: src/main/java/frc/robot/Controls.java [hunk 1]
```diff
@@ -496,7 +496,7 @@ private void configureClimbPivotBindings() {
       setClimbLEDs = Commands.none();
     }
 
-    s.climbPivotSubsystem.setDefaultCommand(s.climbPivotSubsystem.advanceClimbCheck());
+    s.climbPivotSubsystem.setDefaultCommand(s.climbPivotSubsystem.advanceClimbCheck().withName("Check Climb"));
```
Comment (markpete) [inline src/main/java/frc/robot/Controls.java:499]: Make the comment "Advance Climb Check", so that the log comment matches the API making it easier to map to.

**Review by KangarooKoala — APPROVED** [review]
Tested 3/25.
